spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

jwt:
  secret: ${SECRET}

springdoc:
  swagger-ui:
    path: /swagger
    operationsSorter: method
  api-docs:
    path: /api-docs

