create sequence if not exists seq_user_short_id
    as integer;

create sequence if not exists item_item_id_seq;

create sequence if not exists seq_match_short_id;

create table if not exists user_profile
(
    user_uuid uuid not null
        constraint user_profile_pkey
            primary key,
    coin          bigint default 0,
    device_id     varchar(500),
    email         varchar(255),
    name          varchar(255),
    password      varchar(500),
    registered_at timestamp    default now() not null,
    short_id      integer      default nextval
        (
            'seq_user_short_id'::regclass
        ),
    user_status   varchar(255) default 'CREATED':: character varying
);

create table game_mode
(
    name varchar(255) not null
        constraint game_mode_pkey
            primary key
);

INSERT INTO public.game_mode (name) VALUES ('CLASSIC');
INSERT INTO public.game_mode (name) VALUES ('ARCADE');

create table if not exists match
(
    match_uuid      uuid not null
        constraint match_pkey
            primary key,
    registered_at              timestamp default now(),
    coin            bigint,
    difficulty      integer,
    match_short_id  bigint    default nextval('seq_match_short_id'::regclass),
    score           bigint,
    life_taken      bigint,
    watched_ad      boolean,
    game_mode_id    varchar(255)
        constraint game_mode_fk
            references game_mode,
    user_profile_id uuid
        constraint user_profile_fk
            references user_profile
);

create table if not exists item
(
    item_id bigint generated by default as identity
        constraint item_pkey
            primary key,
    name    varchar(255),
    value   bigint
);

alter sequence item_item_id_seq owned by item.item_id;

create table if not exists user_item
(
    id              bigint not null
        constraint user_item_pkey
            primary key,
    registered_at   timestamp,
    item_id         bigint
        constraint item_fk
            references item,
    user_profile_id uuid
        constraint user_profile_fk
            references user_profile
);

create table version
(
    placeholder varchar(255) not null
        constraint version_pkey
            primary key,
    ended_at    timestamp,
    launched_at timestamp default now()
);