create sequence if not exists seq_user_short_id
    as integer;

create sequence if not exists item_item_id_seq;

create sequence if not exists seq_match_short_id;

alter sequence seq_match_short_id owner to postgres;

alter sequence item_item_id_seq owner to postgres;

alter sequence seq_user_short_id owner to postgres;


create table if not exists user_profile
(
    user_uuid
                  uuid
          not
              null
        constraint
            user_profile_pkey
            primary
                key,
    coin
                  bigint
                               default
                                   0,
    device_id
                  varchar(255),
    email         varchar(255),
    name          varchar(255),
    password      varchar(255),
    registered_at timestamp    default now
        (
        ) not null,
    short_id      integer      default nextval
        (
            'seq_user_short_id'::regclass
        ),
    user_status   varchar(255) default 'CREATED':: character varying
);

alter table user_profile
    owner to postgres;

create table game_mode
(
    name varchar(255) not null
        constraint game_mode_pkey
            primary key
);

alter table game_mode
    owner to postgres;

INSERT INTO public.game_mode (name) VALUES ('Classic');
INSERT INTO public.game_mode (name) VALUES ('Arcade');

create table if not exists match
(
    match_uuid      uuid not null
        constraint match_pkey
            primary key,
    at              timestamp default now(),
    coin            bigint,
    difficulty      integer,
    match_short_id  bigint    default nextval('seq_match_short_id'::regclass),
    score           bigint,
    watched_ad      boolean,
    game_mode_id    varchar(255)
        constraint game_mode_fk
            references game_mode,
    user_profile_id uuid
        constraint user_profile_fk
            references user_profile
);

alter table match
    owner to postgres;

create table if not exists item
(
    item_id bigint generated by default as identity
        constraint item_pkey
            primary key,
    name    varchar(255),
    value   bigint
);

alter table item
    owner to postgres;

alter sequence item_item_id_seq owned by item.item_id;

create table if not exists user_item
(
    id              bigint not null
        constraint user_item_pkey
            primary key,
    registered_at   timestamp,
    item_id         bigint
        constraint item_fk
            references item,
    user_profile_id uuid
        constraint user_profile_fk
            references user_profile
);

alter table user_item
    owner to postgres;

create table version
(
    placeholder varchar(255) not null
        constraint version_pkey
            primary key,
    ended_at    timestamp,
    launched_at timestamp default now()
);

alter table version
    owner to postgres;



